package com.example.wikiapp_balondeoro.clases
fun crearClubes(): List<Club>{
        val clubes: List<Club> = listOf(
            Club("Real Madrid", 12, "España"),
            Club("Barcelona", 12, "España"),
            Club("Juventus", 8, "Italia"),
            Club("AC Milan", 8, "Italia"),
            Club("Bayern de Múnich", 5, "Alemania"),
            Club("Manchester United", 4, "Ingraterra"),
            Club("Dynamo de Kiev", 2, "Ucrania"),
            Club("Hamburg", 2, "Alemania"),
            Club("Internazionale", 2, "Italia"),
            Club("Paris Saint-Germain", 2, "Francia"),
            Club("Blackpool", 1, "Inglaterra"),
            Club("Dukla Praga", 1, "República Checa"),
            Club("Dynamo Moscú", 1, "Rusia"),
            Club("Benfica", 1, "Portugal"),
            Club("Ferencváros", 1, "Hungria"),
            Club("Ajax", 1, "Paises Bajos"),
            Club("Borussia Mönchengladbach", 1, "Alemania"),
            Club("Marsella", 1, "Francia"),
            Club("Borussia Dortmund\n", 1, "Alemania"),
            Club("Liverpool\n", 1, "Inglaterra"),
            Club("Inter Miami\n", 1, "Estados Unidos"),
            Club("Manchester City\n", 1, "Inglaterra"),
        )
        return clubes
    }

    fun crearEstadisticas(): List<Estadisticas>{
        val estadisticas: List<Estadisticas> = listOf(
            Estadisticas(17,5,"Blackpool", "FA cup", "Desempeño sobresaliente como extremo, clave en los éxitos del Blackpool"),
            Estadisticas(31,10,"Real Madrid", "LaLiga, Copa de Europa", "Máximo goleador y líder en la consecución de títulos nacionales y europeos"),
            Estadisticas(23,8,"Real Madrid", "LaLiga, Copa de Europa", "Creatividad y goles decisivos en la liga y en la Copa de Europa"),
            Estadisticas(28,9,"Real Madrid", "LaLiga, Copa de Europa", "Máximo goleador y motor ofensivo de Real Madrid en todos los torneos"),
            Estadisticas(19,6,"Barcelona", "Copa de Europa, LaLiga", "Líder en asistencias y goles importantes, clave en los títulos"),
            Estadisticas(19,7,"Juventus", "Serie A, Copa de Italia", "Máximo goleador de la liga y decisivo en partidos de Copa"),
            Estadisticas(16,5,"Dukla Plaga", "Liga Checoslovaca", "Líder del mediocampo, excelente control de juego y goles clave"),
            Estadisticas(0,0,"Dynamo Moscú", "Ninguno", "Sobresaliente actuación como portero, clave en la defensa de su equipo"),
            Estadisticas(26,5,"Manchester United", "FA Cup", "Máximo goleador de la liga, decisivo en victorias importantes"),
            Estadisticas(32,8,"Benfica", "Primeira liga, Copa de europa", "Maximo goleador y figura clave en los titulos europeos del Benfica"),
            Estadisticas(22,6,"Manchester United", "Copa del mundo, FA cup", "Liderazgo y goles decisivos en la copa del mundo y en la liga inglesa"),
            Estadisticas(29,7,"Ferencváros", "Campeonato Hungaro", "Maximo goleador y motor ofensivo del equipo"),
            Estadisticas(28,10,"Manchester United", "Copa de europa, FA cup", "Habilidad, goles y asistencias decisivas en torneos nacionales y europeos"),
            Estadisticas(18,5,"AC Milan", "Coppa Italia", "Goles y asistencias determinantes para la conquista de la coppa italia"),
            Estadisticas(38,9,"Bayern de Múnich", "Bundesliga, Copa de alemania, Copa de europa", "Maximo goleador y lider ofensivo, decisivo en la obtencion de titulos nacionales y europeos"),
            Estadisticas(33,10,"Ajax", "Eredivisie, Copa de europa", "Maximo goelador y creador de juego, figura central en los titulos del Ajax"),
            Estadisticas(14,6,"Bayern de Múnich", "Bundesliga, Copa de europa", "Defensa y mediocampista con liderazgo clave en la obtencion de titulos"),
            Estadisticas(27,12,"Barcelona", "LaLiga, Copa del Rey", "Maximo goleador y generador de juego, fundamental para los titulos del Barça"),
            Estadisticas(22,25,"Barcelona", "LaLiga, SubCampeon del Mundo", "Mejor jugador del mundial 1974"),
            Estadisticas(18,6,"Dynamo de Kiev", "Liga Sovietica", "Maximo goleador y figura ofensiva clave del Dynamo"),
            Estadisticas(15,7,"Bayern de Múnich", "Bundesliga, Copa de europa",  "defensa lider y pieza central en titulos del club"),
            Estadisticas(19,7,"Borussia Mönchengladbach", "Bundesliga, Copa de europa", "Maximo goleador y motor ofensivo del equipo"),
            Estadisticas(17,6,"Hamburg", "Bundesliga", "Maximo goleador de la bundesliga, decisivo en victorias"),
            Estadisticas(20,9,"Hamburg", "Bundesliga", "Maximo goleador de la bundesliga, influencia decisiva en titulos"),
            Estadisticas(29,10,"Bayern de Múnich", "Bundesliga, Copa de Alemania", "Maximo goleador y lider del ataque del Bayern"),
            Estadisticas(27,9,"Bayern de Múnich", "Bundesliga, Copa de Alemania", "Maximo goleador y figura clave en titulos"),
            Estadisticas(20,5,"Juventus", "Serie A, Coppa de Italia", "Maximo goleador y figura en la conquista de titulos y mundial del 1982"),
            Estadisticas(18,6,"Juventus", "Serie A, Coppa de Italia", "Maximo goleador y creador de juego, decisivo para titulos"),
            Estadisticas(19,7,"Juventus", "Serie A, Coppa Italia", "Maximo goleador y lider del equipo"),
            Estadisticas(20,8,"Juventus", "Serie A, Coppa Italia", "Maximo goleador y decisivo en titulos"),
            Estadisticas(25,4,"Dynamo de Kiev", "Liga Sovietica", "Maximo goleador y figura ofensiva clave"),
            Estadisticas(15,5,"AC Milan", "Serie A, Coppa de Italia", "Lider ofensivo y versatil en titulos del club"),
            Estadisticas(26,6,"AC Milan", "Serie A, Coppa de Italia", "Maximo goleador y figura decisiva en titulos"),
            Estadisticas(28,7,"AC Milan", "Serie A, Coppa de Italia", "Maximo goleador y lider del ataque"),
            Estadisticas(22,8,"Internazionale", "Bundesliga, Copa de Alemania, Mundial del 1990", "Liderazgo y desempeño sobresaliente en liga y mundial"),
            Estadisticas(25,6,"Marsella", "Ligue 1, Copa de Francia", "Maximo goleador y figura decisiva"),
            Estadisticas(24,5,"AC Milan", "Serie A, Coppa de Italia", "Maximo goleador y lider del equipo"),
            Estadisticas(21,7,"Juventus", "Serie A, Coppa de Italia", "Creador de juego y goleador clave"),
            Estadisticas(20,6,"Barcelona", "LaLiga, Copa del Rey", "Maximo goleador y figura decisiva"),
            Estadisticas(16,5,"AC Milan", "Serie A, Coppa de Italia", "Maximo goleador y motor ofensivo del equipo"),
            Estadisticas(12,4,"Borussia Dortmund", "Bundesliga, Copa de Alemania", "Lider defensivo y mediocampista clave"),
            Estadisticas(25,7,"Internazionale", "Serie A, Coppa de Italia", "Maximo golador y figura ofensiva"),
            Estadisticas(14,6,"Juventus", "Serie A, Coppa de Italia", "Creatividad y liderazgo decisivo"),
            Estadisticas(24,8,"Barcelona", "LaLiga, Copa del Rey", "Maximo goleador y figura ofensiva"),
            Estadisticas(15,9,"Real Madrid", "LaLiga, Supercopa de España", "Creatividad y asistencias decisivas"),
            Estadisticas(16,7,"Liverpool", "Premier League, FA cup", "Maximo goleador y decisivo en partidos claves"),
            Estadisticas(23,6,"Real Madrid", "LaLiga, Copa del Rey", "Maximo goleador y lider ofensivo"),
            Estadisticas(18,5,"Juventus", "Coppa Italia", "Goles y asistencias determinantes para la conquista de la coppa Italia"),
            Estadisticas(24,6,"AC Milan", "Serie A, Coppa Italia", "Maximo goleador de la liga, figura clave en los titulos nacionales"),
            Estadisticas(26,9,"Barcelona", "LaLiga, Copa del Rey", "Maximo goleador y asistente, lider del equipo"),
            Estadisticas(5,2,"Real Madrid", "Copa del Mundo 2006(Italia), LaLiga", "Liderazgo defensivo y rendimiento destacado en el Mundial"),
            Estadisticas(20,8,"AC Milan", "Serie A,Liga de campeones de la UEFA", "Maximo goleador de la Champions, fugira en titulos nacionales"),
            Estadisticas(42,8,"Manchester United", "Premier League, FA cup,Liga de Campeones de la UEFA", "Maximo goleador de la liga y de la Champions"),
            Estadisticas(38,18,"Barcelona", "LaLiga,Copa del Rey,Liga de Campeones de la UEFA", "Maximo goleador y asistente,figura en titulos nacionales y internacionales "),
            Estadisticas(47,11,"Barcelona", "LaLiga, Supercopa de España", "Maximo goleador y asistente, rendimiento excepcional"),
            Estadisticas(73,29,"Barcelona", "LaLiga,Copa del Rey,Liga de Campeones de la UEFA", "Maximo goleador y asistente,figura en titulos nacionales y internacionales"),
            Estadisticas(91,22,"Barcelona", "LaLiga,Copa del Rey,Supercopa de españa", "Record de goles en un año calendario, rendimiento sobresaliente"),
            Estadisticas(59,15,"Real Madrid", "Copa del Rey", "Maximo goleador,figura clave en los tutilos nacionales"),
            Estadisticas(51,22,"Real Madrid", "Supercopa de España", "Maximo goleador, rendimiento destacado"),
            Estadisticas(58,27,"Barcelona", "LaLiga,Copa del Rey,Liga de Campeones de la UEFA", "Maximo goleador y asistente, figura en titulos nacionales e internacionales"),
            Estadisticas(55,12,"Real Madrid", "LaLiga, Liga de Campeones de la UEFA, Eurocopa 2016", "Maximo goleador, figura clave en titulos nacioneales e internacionales"),
            Estadisticas(55,15,"Real Madrid", "LaLiga, Liga de Campeones de la UEFA, Supercopa de Europa, Supercopa de España", "Maximo goleador, rendimiento sobresaliente"),
            Estadisticas(2,6,"Real Madrid", "Liga de Campeones de la UEFA, Subcampeon mundial 2018", "Liderazgo y rendimiento destacado en liga y mundial"),
            Estadisticas(54,19,"Barcelona", "LaLiga, Supercopa de España", "Maximo goleador y asistente, figura en titulos nacionales"),
            Estadisticas(0,0,"No se otorgo en ese año", "No se otorgo en ese año", "No se otorgo en ese año"),
            Estadisticas(41,17,"Paris Saint-Germain", "Copa America 2021, Ligue 1", "Maximo goeleador y asistente, rendimiento sobresaliente"),
            Estadisticas(44,15,"Real Madrid", "LaLiga, Liga de Campeones de la UEFA, Supercopa de Europa", "Maximo goleador, figura clave en titulos nacionales e internacionales"),
            Estadisticas(30,9,"Inter Miami", "Luegues Cup, Copa de la Liga", "Maximo goleador y asistente, figura en titulos internacionales"),
            Estadisticas(12,7,"Manchester City", "Premier League, FA cup, Liga de Campeones de la UEFA, Eurocopa 2024", "Maximo goleador de la liga, rendiemiento destacado"),
            Estadisticas(27,15,"Paris Saint-Germain", "Ligue 1, Copa de francia, Liga de Campeones de la UEFA", "Maximo goleador y asistente, figura en titulos nacionales e internacionales")
        )
        return estadisticas
    }

fun crearJugadores(){
    val equipos  = crearClubes()
    val estad = crearEstadisticas()
    val jugadores: List<Jugador> = listOf(
        Jugador("Stanley Matthews", "Ingles", listOf(1956), 1, listOf(estad[0])),
        Jugador("Alfredo Stéfano Di Stéfano Laulhé", "Argentino/Español", listOf(1957,1959), 2, listOf(estad[1],estad[3])),
        Jugador("Raymond Kopaszewski", "Frences/Polaco", listOf(1958), 1, listOf(estad[2])),
        Jugador("Luis Suárez Miramontes", "Español", listOf(1960), 1, listOf(estad[4])),
        Jugador("Enrique Omar Sívori", "Argentina/Italiana", listOf(1961), 1, listOf(estad[5])),
        Jugador("Josef Masopust", "Republica Checa", listOf(1962), 1, listOf(estad[6])),
        Jugador("Lev Ivánovich Yashin", "Union Sovietica", listOf(1963), 1, listOf(estad[7])),
        Jugador("Denis Law", "Británica", listOf(1964), 1, listOf(estad[8])),
        Jugador("Eusébio da Silva Ferreira", "Portugal", listOf(1965), 1, listOf(estad[9])),
        Jugador("Robert Charlton", "Ingles", listOf(1966), 1, listOf(estad[10])),
        Jugador("Flórián Albert", "hungaro", listOf(1967), 1, listOf(estad[11])),
        Jugador("George Best", "Norte de Irlanda", listOf(1968), 1, listOf(estad[12])),
        Jugador("Giovanni Rivera", "Italia", listOf(1969), 1, listOf(estad[13])),
        Jugador("Gerhard Müller", "Aleman", listOf(1970), 1, listOf(estad[14])),
        Jugador("Hendrik Johannes Cruijff", "Paises Bajos", listOf(1971,1973,1974), 3, listOf(estad[15],estad[17],estad[18])),
        Jugador("Franz Anton Beckenbauer", "aleman", listOf(1972,1976), 2, listOf(estad[16],estad[20])),
        Jugador("Oleh Volodímirovich Blojín", "Union Sovietica", listOf(1975), 1, listOf(estad[19])),
        Jugador("Allan Rodenkam Simonsen", "dinamarca", listOf(1977), 1, listOf(estad[21])),
        Jugador("Joseph Kevin Keegan", "Ingles", listOf(1978,1979), 2, listOf(estad[22],estad[23])),
        Jugador("Karl-Heinz Rummenigge", "aleman", listOf(1980,1981), 2, listOf(estad[24],estad[25])),
        Jugador("Paolo Rossi", "Italiana", listOf(1982), 1, listOf(estad[26])),
        Jugador("Michel François Platini", "Frances", listOf(1983,1984,1985), 3, listOf(estad[27],estad[28],estad[29])),
        Jugador("Íhor Ivánovich Belánov", "Union Sovietica", listOf(1986), 1, listOf(estad[30])),
        Jugador("Ruud Gullit", "Paises Bajos", listOf(1987), 1, listOf(estad[31])),
        Jugador("Marcel van Basten ", "Paises Bajos", listOf(1988,1989,1992), 3, listOf(estad[32],estad[33],estad[36])),
        Jugador("Lothar Herbert Matthäus", "Aleman", listOf(1990), 1, listOf(estad[34])),
        Jugador("jean-Pierre Papin", "Frances", listOf(1991), 1, listOf(estad[35])),
        Jugador("Roberto Baggio", "Italiano", listOf(1993), 1, listOf(estad[37])),
        Jugador("Hristo Stoichkov", "bulgaro", listOf(1994), 1, listOf(estad[38])),
        Jugador("George Tawlon Manneh Oppong Ousman Weah", "Liberia", listOf(1995), 1, listOf(estad[39])),
        Jugador("Matthias Sammer", "Aleman", listOf(1996), 1, listOf(estad[40])),
        Jugador("Ronaldo Luís Nazário de Lima", "Brazileño", listOf(1997,2002), 2, listOf(estad[41],estad[46])),
        Jugador("Zinedine Yazid Zidane", "Frances", listOf(1998), 1, listOf(estad[42])),
        Jugador("Vítor Borba Ferreira Gomes", "Brazileño", listOf(1999), 1, listOf(estad[43])),
        Jugador("Luís Filipe Madeira Caeiro Figo", "Portugal", listOf(2000), 1, listOf(estad[44])),
        Jugador("Michael James Owen", "Ingles", listOf(2001), 1, listOf(estad[45])),
        Jugador("Pavel Nedvěd", "Republica Checa", listOf(2003), 1, listOf(estad[47])),
        Jugador("Andriy Mykolayovych Shevchenko", "Ucraniano", listOf(2004), 1, listOf(estad[48])),
        Jugador("Ronaldo De Assis Moreira", "Brazileño", listOf(2005), 1, listOf(estad[49])),
        Jugador("Fabio Cannavaro", "Italiano", listOf(2006), 1, listOf(estad[50])),
        Jugador("Ricardo Izecson Dos Santos Leite", "Brazileño", listOf(2007), 1, listOf(estad[51])),
        Jugador("Cristiano Ronaldo dos Santos Aveiro", "Portugal", listOf(2008,2013,2014,2016,2017), 5, listOf(estad[52],estad[57],estad[58],estad[60],estad[61])),
        Jugador("Lionel Andrés Messi Cuccittini", "Argentino", listOf(2009,2010,2011,2012,2015,2019,2021,2023), 8, listOf(estad[53],estad[54],estad[55],estad[56],estad[59],estad[63],estad[64],estad[66])),
        Jugador("Luka Modrić", "Croata", listOf(2018), 1, listOf(estad[62])),
        Jugador("Karim Mostafa Benzema", "Frances", listOf(2022), 1, listOf(estad[65])),
        Jugador("Rodrigo Hernández Cascante", "Español", listOf(2024), 1, listOf(estad[67])),
        Jugador("Masour Ousmane Dembelé", "Frances", listOf(2025), 1, listOf(estad[68])),
    )
}


